sonar.projectKey=HORTOS0_my-devsecops-app
sonar.organization=hortos0
sonar.projectName=my-devsecops-app
sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
